version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
  promotheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "zbl-vol:/tmp/logs"
    depends_on:
      - kafka
volumes:
  zbl-vol:
    external: true


