version: '3.5'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181
  broker:
    image: confluentinc/cp-kafka:5.5.0
    container_name: broker
    ports:
      - "19092:19092"
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,CONNECTIONS_FROM_HOST://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  promotheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "zbl-vol:/tmp/logs"
    depends_on:
      - broker
volumes:
  zbl-vol:
    external: true
networks:
  zoombala:
    name: zoombala


