#kafka config
kafkas:
  topics:
    -
      name: zbl_inward
      numPartitions: 2
      replicafactor: 1
    -
      name: zbl_outward
      numPartitions: 2
      replicafactor: 1
    -
      name: zbl_inward_fail_records
      numPartitions: 2
      replicafactor: 1


