#kafka config
kafkas:
  topics:
    -
      name: zbly_inward
      numPartitions: 2
      replicafactor: 1
    -
      name: zbly_outward
      numPartitions: 2
      replicafactor: 1
    -
      name: zbly_inward_fail_records
      numPartitions: 2
      replicafactor: 1
    -
      name: zbly_order_in
      numPartitions: 2
      replicafactor: 1


