eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

spring:
  application:
    name: zbl-utils
  kafka:
    consumer:
      auto-offset-reset: earliest

server:
  port: 8820




kafka:
    bootstrap:
      server:
        config: localhost:9092
    serializer:
      class:
        config: StringSerializer.class
    value:
      class:
        config: StringSerializer.class




