eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

server:
  port: 8841

spring:
  config:
      import: optional:configserver:http://root:s3cr3t@host.docker.internal:8888/
      label: master
      profile: ${spring.profile.active}
  application:
    name: zbl-utils
  kafka:
    bootstrap-servers: ${kafka_bootstrap_servers:localhost:19092}
#    properties:
#      sasl:
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username=${kafka_username:'admin'} password=${kafka_password:'admin-secret'};
#        mechanism: PLAIN
#      security:
#        protocol: SASL_PLAINTEXT
    consumer:
      auto-offset-reset: latest
      max-poll-records: 1
      fetch-max-wait: 36000
      enable-auto-commit: false
      group-id: mygroup_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    jaas:
      enabled: true
    listener:
      poll-timeout: 1800000
      concurrency: 1
  profile:
    active: native



#kafka:
#    bootstrap:
#      server:
#        config: localhost:9092
#    serializer:
#      class:
#        config: StringSerializer.class
#    value:
#      class:
#        config: StringSerializer.class

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always





