# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
      
      
    - name: Package zbl-config
      run: mvn -B package --file zbl-config/pom.xml 
    - name: Build zbl-registry-pod
      run: mvn -B package --file zbl-registry-pod/pom.xml
#     - name: list file
#       run: ls -lat
#     - name: Build zbl-config Docker image
#       run: docker build . --file zbl-config/Dockerfile --tag zbl-config:$(date +%s)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: kayshaoudocker/zbl-config
      
    - name: Build and push zbl-config Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: zbl-config/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: zbl-registry
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: kayshaoudocker/zbl-registry
    - name: Build and push zbl-registry Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: zbl-registry-pod/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.zbl-registry.outputs.tags }}
        labels: ${{ steps.zbl-registry.outputs.labels }}


    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
   # - name: Update dependency graph
   #   uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
